# Generated by Django 3.2.9 on 2021-11-30 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_project_catagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='catagory',
            new_name='category',
        ),
    ]
